# Variables
variable "vsphere_vcenter" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_datacenter" {}
variable "vsphere_cluster" {}
variable "dns1" {}
variable "dns2" {}
variable "datacenter" {}
variable "datastore" {}
variable "cluster" {}
variable "dvs_vlan" {}
variable "template" {}
variable "hostname" {}
variable "ip_address" {}
variable "gateway" {}
variable "disk_size" {}
variable "netmask" {}
variable "domain" {}
variable "root_size_percentage" {}
variable "var_size_percentage" {}
variable "cpu" {}
